apiVersion: v1
kind: Service
metadata:
  name: streamapi
  labels:
    app: streamapi
    version: v1
spec:
  selector:
    app: streamapi
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP